### ISSUE TITLE
。

### ISSUE THREAD

**Issue by Lee-Akita** [elbert-xiao/Simple-RFCN-PyTorch#1]
How to train my dataset？

**Comment by elbert-xiao** [comment]
1. A relatively simple way is to convert your dataset to VOC format (annotation and image names, etc.),  and then place them in the specified folder. You can refer to the parsing rules of the VOC dataset.
2. Or you can rewrite the `data/dataset.py` module base on your datasets without changing the dataset itself. (Recommend!)

**Comment by Lee-Akita** [comment]
> 1. A relatively simple way is to convert your dataset to VOC format (annotation and image names, etc.),  and then place them in the specified folder. You can refer to the parsing rules of the VOC dataset.
> 2. Or you can rewrite the `data/dataset.py` module base on your datasets without changing the dataset itself. (Recommend!)
