### ISSUE TITLE
how can I get AP?

### ISSUE THREAD

**Issue by fxyp** [elbert-xiao/Simple-RFCN-PyTorch#2]
请问各个类别的AP怎么得到啊？该代码只有一个mAP

**Comment by elbert-xiao** [comment]
#eval_result = rfcn_md_eval(test_dataloader, rfcn_md, test_num=opt.test_num)
可以从eval_result['ap']中获取。

**Comment by fxyp** [comment]
> #eval_result = rfcn_md_eval(test_dataloader, rfcn_md, test_num=opt.test_num) 可以从eval_result['ap']中获取。

这是训练后打印得到的AP吗，不是评估后得到的吗？我在eval_result = rfcn_md_eval(test_dataloader, rfcn_md, test_num=opt.test_num)的后面加了一句print =（“AP:  ",str(eval_result['AP'])），结果还是出错，得不到AP，请问我具体该怎么改代码呀

**Comment by fxyp** [comment]
> > #eval_result = rfcn_md_eval(test_dataloader, rfcn_md, test_num=opt.test_num) 可以从eval_result['ap']中获取。
> 
> 这是训练后打印得到的AP吗，不是评估后得到的吗？我在eval_result = rfcn_md_eval(test_dataloader, rfcn_md, test_num=opt.test_num)的后面加了一句print =（“AP: ",str(eval_result['AP'])），结果还是出错，得不到AP，请问我具体该怎么改代码呀

现在已经好了，应该是ap小写就出来了
